### ISSUE TITLE
Compatibility issue with spack 0.20

### ISSUE THREAD

**Issue by tpadioleau** [pdidev/spack#13]
Using spack 0.20, the local `py-distributed` package seems to be outdated, I have an issue with the deleted `py-contextvars` dependency of this package.

I would propose that we make a backup of the current state that works with spack 0.19 in a dedicated branch and a new branch 0.20 without our custom recipes of python packages.

**Comment by tpadioleau** [comment]
I guess we can have a discussion about the packages that are already in the main spack repository. Some of them are necessary for DEISA. I also found that `sionlib` is already in the main repo.

**Comment by jbigot** [comment]
Then I'll remove sionlib, no need to keep it here

**Comment by jbigot** [comment]
py-distributed here is the receipe for a fork required for Deisa

**Comment by tpadioleau** [comment]
Our version seems more evolved than the spack 0.20.0 one. Maybe we should contribute to the main repo version ?

**Comment by jbigot** [comment]
our version of what?

**Comment by jbigot** [comment]
but, yes, upstreaming most receipes would be great

**Comment by tpadioleau** [comment]
> our version of what?

`sionlib`

**Comment by GueroudjiAmal** [comment]
There are other needed packages missing in spack 0.20 in addition to the `py-contextvars` the `py-ordereddict`, `py-singledispatch`, `py-futures` are needed for py-dask

**Comment by GueroudjiAmal** [comment]
Adding those packages install correctly pdiplugin-deisa and dependencies 
(I just took them an older version of spack packages (https://github.com/spack/spack/blob/v0.16.0/var/spack/repos/builtin/packages/)

**Comment by tpadioleau** [comment]
That may do the trick but I wonder if it is reasonable on the mid/long term.

**Comment by GueroudjiAmal** [comment]
Actually yeah, at some point it may be interesting to pull request deisa-external tasks feature to dask distributed this may we use a maintained spack package of dask and dependencies ...
