### ISSUE TITLE
`sionlib` contribution to the main recipe

### ISSUE THREAD

**Issue by tpadioleau** [pdidev/spack#15]
The package `sionlib` is available in the main spack repository. Our version seems to handle more features. @pramodk you seem to be the main maitainer, what do you think ?

**Comment by pramodk** [comment]
Hello @tpadioleau!

I think it would be great to have changes upstreamed in main spack as well?

**Comment by tpadioleau** [comment]
I agree as well

**Comment by tpadioleau** [comment]
I can open a PR on the main spack repo and ask for your review

**Comment by jbigot** [comment]
the Sionlib PDI plugin is deprecated and will be removed in the next PDI release, the recipe will be removed from the main branch then. If you need it, please speak now or forever hold your peace
