### ISSUE TITLE
Compilation error on PDI version 1.6.0 with spack 0.22.0

### ISSUE THREAD

**Issue by tpadioleau** [pdidev/spack#17]
The library pybind11 changed the definition of `PyArrayDescr_Proxy` in version v2.12.0, see https://github.com/pybind/pybind11/blob/v2.12.0/include/pybind11/numpy.h. Spack introduces version v2.12.0 of pybind11 in version v0.22.0.  Therefore PDI version v1.6.0 with Python support does not compile fine from spack version v0.22.0.

**Comment by jbigot** [comment]
Yes it's fixed in 1.7. we should add a conflict for older PDI versions
