### ISSUE TITLE
Discussion about contributing to spack

### ISSUE THREAD

**Issue by tpadioleau** [pdidev/spack#19]
I find it unclear what version of spack we are supporting. In my opinion contributing to the main spack repository should be considered even though it would be restrictive to get the latest PDI release.

cc @jbigot @benoitmartin88

**Comment by jbigot** [comment]
We support spack 0.18+ for PDI recipes and their dependencies. The rest is just not tested.
The version supported for PDI should indeed be stated more clearly.

We should also upstream those packages, but I believe support for recent versions of PDI on old spack often available on clusters should also be kept through this repo.

For the non PDI recipes (gysela mostly), we should see if it makes sense to keep them.

**Comment by tpadioleau** [comment]
> We support spack 0.18+ for PDI recipes and their dependencies. The rest is just not tested. The version supported for PDI should indeed be stated more clearly.

Do you include `pdiplugin-deisa` ? I don't think it works fine for spack >= 0.20. The problem is about the dependencies of `pdiplugin-deisa`, some packages do not exist anymore. For example, if I declare the repository as a spack repo, then I cannot install `py-dask`.

I currently use the branches `releases/0.x` to make it work.

**Comment by jbigot** [comment]
No, you're right that `pdiplugin-deisa` currently doesn't follow the policy for the rest of PDI. We will also never be able to upstream it since it depends on a fork of Dask.

**Comment by tpadioleau** [comment]
In the meantime could we split the recipes into different spack repos ?

**Comment by jbigot** [comment]
I propose to only keep well tested packages that do not overlap with official packages in the main branch. This means that:

the following recipes will be kept as-is:
* `paraconf`
* `pdi`
* `pdiplugin-decl-hdf5`
* `pdiplugin-decl-netcdf`
* `pdiplugin-mpi`
* `pdiplugin-pycall`
* `pdiplugin-serialize`
* `pdiplugin-set-value`
* `pdiplugin-trace`

tests should be added for the following recipes:
* `zpp`

the following recipes will be kept in a dedicated branch:
* `pdiplugin-deisa`
* `py-dask`
* `py-dask-ml`
* `py-deisa`
* `py-distributed`

We are open to keep the following recipes if someone is identified as maintainer:
* `gysela`
* `voicexx`
* `ddc`
* `layout-contiguous`
* `mdspan`

the following recipes will be removed:
* `flowvr`
* `pdiplugin-decl-sion`
* `pdiplugin-flowvr`
* `pdiplugin-fti`
* `pdiplugin-user-code`
* `sionlib`
