### ISSUE TITLE
Disable MPI dependency for the plugin `pdiplugin-decl-hdf5`

### ISSUE THREAD

**Issue by tpadioleau** [pdidev/spack#8]
I would suggest to explicitly disable MPI when the option is disabled for the plugin `pdiplugin-decl-hdf5` with something like
```python3
depends_on('hdf5 ~mpi', type=('build', 'link', 'run'), when='~mpi') 
```
because the default behaviour of the HDF5 recipe is to enable MPI.

**Comment by jbigot** [comment]
this would prevent re-using a perfectly fine parallel HDF5. If spack offers support for changing the default without making it a requirement, that's what we should aim for
